OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Klinik
    Domain: klinik.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2

  - Name: Akademik
    Domain: akademik.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2

  - Name: Mahasiswa
    Domain: mahasiswa.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2
